version = 0.1

# Build (default configured for local dev)
[default.build.parameters]
use_container = true
parameter_overrides = [
    'Platform=local',
    'Stage=dev',
    'DockerTag=latest',
    'Architetcure=__TARGETARCH__' # Change according to your TARGETARCH environment variable
]

[dev.build.parameters]
use_container = true
parameter_overrides = [
    'Stage=dev',
    'DockerTag=latest'
]

[dev.build.parameters]
use_container = true
parameter_overrides = [
    'Stage=staging',
    'DockerTag=latest'
]

[prod.build.parameters]
use_container = true

# Local start-api (default configured for local dev)

[default.local_start_api.parameters]
warm_containers = 'EAGER'
container_host = 'host.docker.internal'  # Use for Mac only, else remove
parameter_overrides = [
    'Platform=local',
    'Stage=dev',
    'DockerTag=latest',
    'Architetcure=__TARGETARCH__' # Change according to arm64 or x86_64 to match with your TARGETARCH
]

# AWS deploy

[dev.deploy.parameters]
stack_name = 'greeting-service'
region = 'eu-west-1'    # Set to primary/default region and override when to deploying to other regions
image_repository = '__DEV_ACCOUNT_ID__.dkr.ecr.eu-west-1.amazonaws.com/greeting'  # replace __ACCOUNT_ID__ with AWS dev account id
parameter_overrides = [
    'Stage=dev',
    'DockerTag=latest'
]

[staging.deploy.parameters]
stack_name = 'greeting-service'
region = 'us-east-1'    # Set to primary/default region and override when to deploying to other regions
image_repository = '__STAGING_ACCOUNT_ID__.dkr.ecr.us-east-1.amazonaws.com/greeting'  # replace __ACCOUNT_ID__ with AWS dev account id
parameter_overrides = [
    'Stage=staging',
    'DockerTag=latest'
]

[prod.deploy.parameters]
stack_name = 'greeting-service'
region = 'us-east-1'    # Set to primary/default region and override when to deploying to other regions
image_repository = '__PROD_ACCOUNT_ID__.dkr.ecr.us-east-1.amazonaws.com/greeting'  # replace __ACCOUNT_ID__ with AWS dev account id
