# SAM Template used by GithubActions
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Greeting Service
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Globals:
  Function:
    Timeout: 10

Parameters:
  Stage:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment stage of the application

  Platform:
    Type: String
    Default: AWS
    AllowedValues:
      - AWS
      - local
    Description: Platform where the Lambda function is deployed

  DockerTag:
    Type: String
    Description: Docker image tag - Use package version for cloud deployments and any value for local dev deployments

  Architecture:
    Type: String
    Default: x86_64 # to go with Github Actions amd64
    AllowedValues:
      - x86_64 
      - arm64
    Description: Architecture 

Resources:
  GreetingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
  
  GreetingLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "greeting"
      PackageType: Image
      ImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/greeting:${DockerTag}'
      Role: !Sub arn:aws:iam::${AWS:AccountId}:role/greeting-lambda-role
      Architectures:
        - !Ref Architecture  
      Environment:
        Variables:
          PLATFORM: !Ref Platform
          STAGE: !Ref Stage
          SERVICE_NAME: greeting
      Events:
        HelloNamePath:
          Type: Api
          Properties:
            Path: /hello/{name}
            Method: GET
            RestApiId:
              Ref: GreetingApi
        HelloPath:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId:
              Ref: GreetingApi
    Metadata:
      Dockerfile: ./services/greeting/Dockerfile
      DockerContext: ../../       # Set docker context to monorepo root to include local packages
      DockerTag: !Ref DockerTag   # Set DockerTage to package version when deploying to AWS

Outputs:
  GreetingApi:
    Description: "API Gateway endpoint URL for Greeting function"
    Value: !Sub "https://${GreetingApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
  GreetingFunction:
    Description: "Greeting Lambda Function ARN"
    Value: !GetAtt GreetingLambda.Arn
