AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Greeting Service
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Globals:
  Function:
    Timeout: 10

Parameters:
  Stage:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment stage of the application

  Platform:
    Type: String
    Default: AWS
    AllowedValues:
      - AWS
      - local
    Description: Platform where the Lambda function is deployed

Resources:
  GreetingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage

  GreetingLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: greeting.lambda_handler.handler
      Runtime: python3.12
      Architectures:
        - arm64
      Environment:
        Variables:
          PLATFORM: !Ref Platform
          STAGE: !Ref Stage
          SERVICE_NAME: greeting
      CodeUri: .
      Events:
        HelloNamePath:
          Type: Api
          Properties:
            Path: /hello/{name}
            Method: GET
            RestApiId:
              Ref: GreetingApi
        HelloPath:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId:
              Ref: GreetingApi