AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Greeting Service
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 5
Resources:
  GreetingFlaskLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: greeting.lambda_handler.handler
      Runtime: python3.10
      Architectures:
        - arm64
      Environment:
        Variables:
          PLATFORM: AWS
          ENVIRONMENT: prod
          SERVICE_NAME: greeting
      CodeUri: .
      Events:
        HelloNamePath:
          Type: Api
          Properties:
            Path: /hello/{name}
            Method: GET
        HelloPath:
          Type: Api
          Properties:
            Path: /hello
            Method: GET