[tool.poetry]
name = "environment"
version = "0.1.0"
description = "Environment Variables"
authors = ["Limor Lahiani"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv="1.0.1"
jsonify = "0.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
