[tool.poetry]
name = "environment"
version = "0.1.0"
description = "Service Environment"
authors = ["Limor Lahiani"]
readme = "README.md"

[tool.semantic_release]
version_variable = "pyproject.toml:tool.poetry.version"
changelog_file = "CHANGELOG.md"

[tool.poetry.dependencies]
python = "^3.12"
python-dotenv="1.0.1"
jsonify = "0.5"

[tool.poetry.dev-dependencies]
pytest = "8.2.0"
pytest-asyncio = "0.23.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
