name: Deploy to Dev & Staging

on:
  # workflow_run:
  #   workflows: ["CI"]
  #   types:
  #     - completed
  push:
    branches: [main]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  pull-requests: write  # This allows the workflow to comment on PRs

jobs:
  check-terraform-changes:
    runs-on: ubuntu-latest
    outputs:
      terraform_changed: ${{ steps.check.outputs.terraform_changed }}
    steps:
      - name: Check-out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full checkout

      - name: Check for changes in infra/terraform
        id: check
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q '^infra/terraform/'; then
            echo "terraform_changed=true" >> $GITHUB_OUTPUT
          else
            echo "terraform_changed=false" >> $GITHUB_OUTPUT

  terraform-apply:
    name: Terraform Apply - ${{ matrix.environment }}
    #if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.pull_requests[0].changed_files.* matches 'infra/terraform/**' }}
    needs: [check-terraform-changes]
    if: needs.check-terraform-changes.outputs.terraform_changed == 'true'
    strategy:
      matrix:
        environment: [dev, staging]
    uses: ./.github/workflows/terraform-apply-reusable.yml
    with:
      environment: ${{ matrix.environment }}

# TODO: Add Deploy Services
