name: Pre-build Dev Container

on:
  workflow_dispatch:  # Allows manual triggering
  workflow_call:      # Allows this workflow to be called by other workflows (e.g. CI when devcontainer has changed)


permissions:
  id-token: write # Required for requesting the JWT
  contents: read  # Required for actions/checkout
  packages: write # Required for publishing to package/container registry

jobs:
  pre-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set-up Devcontainer Environment Variables
        run: |
          echo "PWD=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
          cp .devcontainer/.env.ci .devcontainer/.env
          echo ".devcontainer/.env:"
          cat .devcontainer/.env

      - name: Pre-build Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/limorl/monorepo-python-sample-devcontainer
          cacheFrom: ghcr.io/limorl/monorepo-python-sample-devcontainer
          push: always
