name: Pre-build Dev Container

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set-up Devcontainer Environment Variables
        run: |
          echo "PWD=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
          cp .devcontainer/.env.ci .devcontainer/.env
          echo ".devcontainer/.env:"
          cat .devcontainer/.env
    
      - name: Pre-build Dev Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/limorl/monorepo-python-sample-devcontainer
          cacheFrom: ghcr.io/limorl/monorepo-python-sample-devcontainer
          push: always