name: Terraform Plan - Dev, Primary Region

# on:

on:
  pull_request:
    branches: [ "main" ]
    paths: [ "infra/terraform/**" ]

  # workflow_dispatch:
  #   inputs:
  #     stage:
  #       description: 'Stage [dev | staging | prod]'
  #       required: true
  #       type: string

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform-deploy-to-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
            role-session-name: GithubWorkflow-TerraformDeployment-Dev
            aws-region: ${{ vars.AWS_PRIMARY_REGION }}
      
      # - name: Create .env File
      #   run: |
      #     cp .devcontainer/.env.ci .devcontainer/.env

      # - name: Terraform init, validate plan
      #   uses: devcontainers/ci@v0.3
      #   with:
      #     runCmd: terraform init && terraform plan
      
      # - uses: trstringer/manual-approval@v1
      #   with:
      #     secret: ${{ github.TOKEN }}
      #     approvers: limorl
      #     minimum-approvals: 1
      #     issue-title: "Deploying infra to Dev"
      #     issue-body: "Review the terraform plan, then approve or deny the deployment to prod."
      #     exclude-workflow-initiator-as-approver: false
  
  # TODO (@limorl): add deployment to `staging` and `prod`