name: Terraform Plan to {env}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      terraform_changed:
        required: true
        type: string

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform-plan:
    name: Plan
    if: inputs.terraform_changed == 'true'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
          role-session-name: GithubWorkflow-TerraformPlan-${{ inputs.environment }}
          aws-region: ${{ vars.AWS_PRIMARY_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: Terraform Init
        id: terraform-init
        working-directory: ./infra/terraform/environments/${{ inputs.environment }}
        run: terraform init

      - name: Terraform Format
        id: terraform-fmt
        working-directory: ./infra/terraform/environments/${{ inputs.environment }}
        run: terraform fmt

      - name: Terraform Validate
        id: terraform-validate
        working-directory: ./infra/terraform/environments/${{ inputs.environment }}
        run: terraform validate
      
      - name: Terraform Plan
        id: terraform-plan
        working-directory: ./infra/terraform/environments/${{ inputs.environment }}
        run: terraform plan -var-file=terraform.tfvars -out=${{ inputs.environment }}.tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.environment }}.tfplan
          path: ./infra/terraform/environments/${{ inputs.environment }}/${{ inputs.environment }}.tfplan
