name: Terraform Deployment - To Primary Region of Environment (Stage)

# on:

on:
  pull_request:
    branches: [ "main" ]
    paths: [ "infra/terraform/**" ]
  push:
    branches: [ "main" ]
    paths: [ "infra/terraform/**" ]

  # workflow_dispatch:
  #   inputs:
  #     stage:
  #       description: 'Stage [dev | staging | prod]'
  #       required: true
  #       type: string

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform-plan-dev:
    name: Terraform Plan - Dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
            role-session-name: GithubWorkflow-TerraformDeployment-Dev
            aws-region: ${{ vars.AWS_PRIMARY_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform-version: 1.7.5

      - name: Terraform fmt
        run: |
          cd infra/terraform
          terraform fmt

      - name: Terraform init
        run: terraform init -backend-config=backend.dev.tfvars

      - name: Terraform Validate
        run: terraform validate
  
  terraform-deploy-dev:
    name: Terraform Deploy - Dev
    needs: terraform-plan-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
          role-session-name: GithubWorkflow-TerraformDeployment-Dev
          aws-region: ${{ vars.AWS_PRIMARY_REGION }}
      - name: Initialise project and deploy terraform
        run: |
          cd infra/terraform
          terraform fmt
          terraform init
          terraform apply -backend-config=backend.dev.tfvars
      
      
      # - name: Create .env File
      #   run: |
      #     cp .devcontainer/.env.ci .devcontainer/.env

      # - name: Terraform init, validate plan
      #   uses: devcontainers/ci@v0.3
      #   with:
      #     runCmd: terraform init && terraform plan
      
      # - uses: trstringer/manual-approval@v1
      #   with:
      #     secret: ${{ github.TOKEN }}
      #     approvers: limorl
      #     minimum-approvals: 1
      #     issue-title: "Deploying infra to Dev"
      #     issue-body: "Review the terraform plan, then approve or deny the deployment to prod."
      #     exclude-workflow-initiator-as-approver: false
  
  # TODO (@limorl): add deployment to `staging` and `prod`