name: Terraform Deployment

on:
  pull_request:
    branches: [main]
    paths: ["infra/terraform/**"]
  push:
    branches: [main]
    paths: ["infra/terraform/**"]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  pull-requests: write  # This allows the workflow to comment on PRs

jobs:
  plan:
    name: Terraform Plan - ${{ matrix.environment }}
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        environment: [dev]  # [dev, staging, prod] TODO (@limorl): Enable all three envs
    uses: ./.github/workflows/terraform-deployment-reusable.yml
    with:
      environment: ${{ matrix.environment }}
      plan_only: true

  apply:
    name: Terraform Apply - ${{ matrix.environment }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [plan]
    strategy:
      matrix:
        environment: [dev]  # [dev, staging] TODO (@limorl): Enable on dev and staging
    uses: ./.github/workflows/terraform-deployment-reusable.yml
    with:
      environment: ${{ matrix.environment }}
      plan_only: false

  apply-prod:
    name: Terraform Apply - prod
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [plan]
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/terraform-deployment-reusable.yml
    with:
      environment: prod
      plan_only: false
