name: Terraform Plan - Reusable Across Environments

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
          role-session-name: GithubWorkflow-TerraformPlan-${{ inputs.environment }}
          aws-region: ${{ vars.AWS_PRIMARY_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        id: terraform-init
        working-directory: ./infra/terraform
        run: terraform init

      - name: Terraform Format
        id: terraform-fmt
        working-directory: ./infra/terraform
        run: terraform fmt

      - name: Terraform Validate
        id: terraform-validate
        working-directory: ./infra/terraform
        run: terraform validate
      
      - name: Terraform Plan
        id: terraform-plan
        working-directory: ./infra/terraform
        run: terraform plan -var-file=environments/${{ inputs.environment }}/terraform.tfvars -out=${{ inputs.environment }}.tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.environment }}.tfplan
          path: ./infra/terraform/${{ inputs.environment }}.tfplan

      - name: Notify success
        if: success() 
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"terraform-plan-${{ inputs.environment }}-success", "client_payload": {"environment": "${{ github.event.inputs.environment }}"} }'
